amplify auto deployment

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -51,3 +51,18 @@ jobs:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: "us-east-2"
+
+      - name: Deploy to Amplify 
+        run: |
+          APP_ID="${{ secrets.APP_ID }}"
+          BRANCH_NAME="main"
+
+          JOB_ID=$(aws amplify start-job --app-id $APP_ID --branch-name $BRANCH_NAME --job-type RELEASE | jq -r '.jobSummary.jobId')
+
+          JOB_STATUS=$(aws amplify get-job --app-id $APP_ID --branch-name $BRANCH_NAME --job-id $JOB_ID | jq -r '.job.summary.status')
+          echo "Amplify job finished with status: $JOB_STATUS"
+
+          if [ "$JOB_STATUS" != "SUCCEED" ]; then
+            echo "Amplify deployment failed."
+            exit 1
+          fi
